# Generated by Django 5.2.6 on 2025-09-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0002_alter_image_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
