# Generated by Django 5.2.6 on 2025-09-21 08:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0003_remove_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
